add aws openidc

diff --git a/.github/workflows/performance-test.yml b/.github/workflows/performance-test.yml
--- a/.github/workflows/performance-test.yml
+++ b/.github/workflows/performance-test.yml
@@ -13,8 +13,9 @@ on:
     - '**/*.go'
     - '**/*.java'
   workflow_dispatch:
-
-
+permissions:
+  id-token: write
+  contents: read
 jobs:
   performance-tests:
     runs-on: ubuntu-latest
@@ -59,6 +60,16 @@ jobs:
         echo "-------------------------"
         echo "✅ VPN setup complete - interface established"
 
+    - name: Configure AWS Credentials
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        role-session-name: performance_test_gh
+        role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
+        aws-region: ap-south-1
+        run: |
+          echo "AWS Credentials configured"
+          aws sts get-caller-identity
+
     - name: Install Go Dependencies
       run: go mod download
 
@@ -98,10 +109,10 @@ jobs:
 
     - name: Create destination.json from secrets
       run: |
-        echo '${{ secrets.DESTINATION_JSON }}' > ./drivers/postgres/internal/testconfig/destination.json
-        echo '${{ secrets.DESTINATION_JSON }}' > ./drivers/mysql/internal/testconfig/destination.json
-        echo '${{ secrets.DESTINATION_JSON }}' > ./drivers/oracle/internal/testconfig/destination.json
-        echo '${{ secrets.DESTINATION_JSON }}' > ./drivers/mongodb/internal/testconfig/destination.json
+        # echo '${{ secrets.DESTINATION_JSON }}' > ./drivers/postgres/internal/testconfig/destination.json
+        echo '${{ secrets.MYSQL_DESTINATION_JSON }}' > ./drivers/mysql/internal/testconfig/destination.json
+        # echo '${{ secrets.DESTINATION_JSON }}' > ./drivers/oracle/internal/testconfig/destination.json
+        # echo '${{ secrets.DESTINATION_JSON }}' > ./drivers/mongodb/internal/testconfig/destination.json
 
     - name: Create benchmark files
       run: |
@@ -116,12 +127,20 @@ jobs:
 
     - name: Run Performance Tests
       run: |
-        go test -v -p 2 ./drivers/mysql/internal/...  ./drivers/mongodb/internal/... -timeout 0 -run 'Performance'
-        go test -v -p 2 ./drivers/oracle/internal/...  ./drivers/postgres/internal/... -timeout 0 -run 'Performance'
+        go test -v ./drivers/mysql/internal/... -timeout 0 -run 'Performance'
+        # go test -v -p 2 ./drivers/mysql/internal/...  ./drivers/mongodb/internal/... -timeout 0 -run 'Performance'
+        # go test -v -p 2 ./drivers/oracle/internal/...  ./drivers/postgres/internal/... -timeout 0 -run 'Performance'
 
     - name: Cleanup
       if: always()
       run: |
+        # Drop database from catalog
+        aws glue delete-database --name performance_mysql || echo "failed to delete database"
+        # aws glue delete-database --name performance_postgres || echo "failed to delete database"
+        # aws glue delete-database --name performance_oracle || echo "failed to delete database"
+        # aws glue delete-database --name performance_mongodb || echo "failed to delete database"
+        echo "Catalog cleanup completed"
+
         # VPN Cleanup
         sudo pkill -f "openvpn.*client.ovpn" || true
         sudo rm -rf /etc/openvpn/client/ /var/log/openvpn-client.log || true
